//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xaminer.App.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xaminer.App.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeftijd.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency.
        /// </summary>
        public static string Agency {
            get {
                return ResourceManager.GetString("Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructieset.
        /// </summary>
        public static string Architecture {
            get {
                return ResourceManager.GetString("Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug naar startpagina.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDSM.
        /// </summary>
        public static string BDSM {
            get {
                return ResourceManager.GetString("BDSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toegevoegd.
        /// </summary>
        public static string ChangeAdded {
            get {
                return ResourceManager.GetString("ChangeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen.
        /// </summary>
        public static string ChangeNone {
            get {
                return ResourceManager.GetString("ChangeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijderd.
        /// </summary>
        public static string ChangeRemoved {
            get {
                return ResourceManager.GetString("ChangeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewijzigd.
        /// </summary>
        public static string ChangeUpdated {
            get {
                return ResourceManager.GetString("ChangeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexbioscoop.
        /// </summary>
        public static string Cinema {
            get {
                return ResourceManager.GetString("Cinema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluiten.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stel.
        /// </summary>
        public static string Couple {
            get {
                return ResourceManager.GetString("Couple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stellen.
        /// </summary>
        public static string Couples {
            get {
                return ResourceManager.GetString("Couples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijderen.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omschrijving.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamant.
        /// </summary>
        public static string Diamond {
            get {
                return ResourceManager.GetString("Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusief.
        /// </summary>
        public static string DiamondExclusive {
            get {
                return ResourceManager.GetString("DiamondExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string DiamondPremium {
            get {
                return ResourceManager.GetString("DiamondPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen.
        /// </summary>
        public static string DiamondUnset {
            get {
                return ResourceManager.GetString("DiamondUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand kon niet gedownload worden.
        /// </summary>
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeg.
        /// </summary>
        public static string Empy {
            get {
                return ResourceManager.GetString("Empy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erotische massage.
        /// </summary>
        public static string EroticMassage {
            get {
                return ResourceManager.GetString("EroticMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foutmelding.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! 🙊 Er trad een fout op.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escort.
        /// </summary>
        public static string Escort {
            get {
                return ResourceManager.GetString("Escort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorieten.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrouw.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrouwen.
        /// </summary>
        public static string Females {
            get {
                return ResourceManager.GetString("Females", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaste lijn.
        /// </summary>
        public static string FixedLine {
            get {
                return ResourceManager.GetString("FixedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De 2 bestands hashes komen niet overeen.
        /// </summary>
        public static string HashCompareFailed {
            get {
                return ResourceManager.GetString("HashCompareFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prive ontvangst.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startpagina.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In real life (IRL) statistieken.
        /// </summary>
        public static string IRLStats {
            get {
                return ResourceManager.GetString("IRLStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon laatste resultaat (plaats: {0}, aantal wijzigingen: {1}).
        /// </summary>
        public static string LastResult {
            get {
                return ResourceManager.GetString("LastResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laatste bezoek.
        /// </summary>
        public static string LastVisit {
            get {
                return ResourceManager.GetString("LastVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mannen.
        /// </summary>
        public static string Males {
            get {
                return ResourceManager.GetString("Males", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massagesalon.
        /// </summary>
        public static string MassageClub {
            get {
                return ResourceManager.GetString("MassageClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobiel.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitgesloten.
        /// </summary>
        public static string NewExluded {
            get {
                return ResourceManager.GetString("NewExluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw vermeld.
        /// </summary>
        public static string NewIncluded {
            get {
                return ResourceManager.GetString("NewIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online statistieken.
        /// </summary>
        public static string OnlineStats {
            get {
                return ResourceManager.GetString("OnlineStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagina link.
        /// </summary>
        public static string PageUrl {
            get {
                return ResourceManager.GetString("PageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaats.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profielfoto.
        /// </summary>
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschap.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorzieningen.
        /// </summary>
        public static string Providings {
            get {
                return ResourceManager.GetString("Providings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoekopdracht (plaatsnaam).
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beoordeling.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raamprostitutie.
        /// </summary>
        public static string RedLights {
            get {
                return ResourceManager.GetString("RedLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vernieuwen.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultaten.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shemale.
        /// </summary>
        public static string Shemale {
            get {
                return ResourceManager.GetString("Shemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shemales.
        /// </summary>
        public static string Shemales {
            get {
                return ResourceManager.GetString("Shemales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon fouten.
        /// </summary>
        public static string ShowErrors {
            get {
                return ResourceManager.GetString("ShowErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onbekend.
        /// </summary>
        public static string Unkown {
            get {
                return ResourceManager.GetString("Unkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatie updaten.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update beschikbaar.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update voortgang.
        /// </summary>
        public static string UpdateProgress {
            get {
                return ResourceManager.GetString("UpdateProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waarden.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versie.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual.
        /// </summary>
        public static string Virtual {
            get {
                return ResourceManager.GetString("Virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Sex.
        /// </summary>
        public static string VirtualSex {
            get {
                return ResourceManager.GetString("VirtualSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezoeken.
        /// </summary>
        public static string Visits {
            get {
                return ResourceManager.GetString("Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
